name: 'Quill Action'
description: 'Quill Action for mobile development'
author: 'wcyn'

# Define your inputs here.
inputs:
  build-platform:
    description: "Which build platform to use. Options are: 'flutter'"
    required: true
    default: 'flutter'
  gdrive-sa-key:
    description: "Key to authorize access to Google Drive folder"
    required: true

# Define your outputs here.
outputs:
  emulator-link:
    description: 'A link to the emulator running the built mobile app'

runs:
  using: docker
  image: Dockerfile
  env:
    INPUT_BUILD_PLATFORM: ${{ inputs.build-platform }}
