name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test-docker:
    name: Docker Tests
    runs-on: ubuntu-latest

    # Run a local registry to push to
    services:
      registry:
        image: registry:2
        ports:
          - 5001:5000

    env:
      TEST_TAG: localhost:5001/actions/container-action:latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Docker BuildX
        id: setup-buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true
          driver-opts: network=host

      - name: Build the Container
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.TEST_TAG }}

      - name: Run the Container
        id: run
        env:
          INPUT_WHO_TO_GREET: Mona Lisa Octocat
        run: |
          docker run \
            --env INPUT_GDRIVE_SA_KEY="${{ env.INPUT_GDRIVE_SA_KEY }}" \
            --env INPUT_GDRIVE_FOLDER_ID="${{ env.INPUT_GDRIVE_FOLDER_ID }}" \
            --env INPUT_GDRIVE_FILENAME="${{ env.INPUT_GDRIVE_FILENAME }}" \ # Implement ability for paths
            --env INPUT_GDRIVE_FILE_OR_FOLDER="${{ env.INPUT_GDRIVE_FILE_OR_FOLDER }}" \
            --rm ${{ env.TEST_TAG }}

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Test Local Action
        id: test-action
        uses: ./
        with:
          gdrive_sa_key: "***"
          gdrive_filename: "test.txt"
          gdrive_folder_id: "testID"

      - name: Print Output
        id: output
        run: echo "${{ steps.test-action.outputs.gdrive_new_file_id }}"
